### ISSUE TITLE
Bug: MechJeb different dV stats in VAB and Launch/TWR not updating on thrust limit change.

### ISSUE THREAD

**Issue by Nhawks1717** [MuMech/MechJeb2#617]
So I've been encountering the first part of my bug report for quite some time now, hoping that it'd be fixed in a new release or one of the dev builds, I waited on submitting an issue. Given that it hasn't been fixed yet I'd like to bring to your attention a bug I'm encountering where my DeltaV is calculated different from when I have my rocket in the VAB and when I have it on the launch pad, shown in these images.
![](http://i.imgur.com/DHzXbXo.jpg)
![](http://i.imgur.com/wiS20xI.jpg)

I am using Dev build 474 and have encountered this since starting my KSP 1.0.x gameplay, I never encountered this issue on the old aero system (possibly the cause??). 

Now for the second part to my report I am also experiencing an issue where the TWR calculations are not updating when changing the thrust limits on engines like it used to. I just starting experiencing this bug and have no clue as to what could be the issue with it. 

Thats all I got, [here](http://www.mediafire.com/view/jgioccu25kbz9d8/output_log.txt) is my output log. If you need any other information I'll be happy to give it, thanks!

**Comment by sarbian** [comment]
The TWR/EngineThrust is a mistake on my end
I guess the editor / flght change comes from a mass change. It would help to have the same screen shot with all the stats displayed

**Comment by sarbian** [comment]
Sharing the craft file and the used mods would help too

**Comment by Nhawks1717** [comment]
Sorry it took me so long to get back to you. Here is what you asked for, I notice now that the mass of the vessel is changing in between scenes so that is probably what is miscalculating my DeltaV.
![](http://i.imgur.com/ecgKBCx.jpg)
![](http://i.imgur.com/sgKIpZg.jpg)

And [here](http://www.mediafire.com/download/8finph77nl749sm/USIVFT_Redstone_II.craft) is the craft file. By mods I'm using I'm guessing the ones that are being used on the ship which is:
SpaceY
Proc Fairings
FASA Launch Clamps and Towers
Near Future Solar

Hope that helps! If you need anything else just let me know, thanks for your help as well!

**Comment by sarbian** [comment]
I won't have the time to check today but I pushed a new dev version that change a few mass related things and that may fix this bug.

**Comment by Nhawks1717** [comment]
Alright I'll check it when I get home and give you an update to see if it's fixed.

**Comment by Nhawks1717** [comment]
Awesome! This fixed both of the issues, thanks sarbian!!

**Comment by Nhawks1717** [comment]
So unfortunatly the bug is back in the recent versions. I tried on 2.5.3 and now I'm using Dev 496 and I'm getting the different read-outs on my DeltaV stats. As seen below.
![](http://i.imgur.com/KRzRsES.jpg)
![](http://i.imgur.com/dArHUjD.png)
